azerothcore/wiki

_includes/git-wiki/defines/defines.html
_includes/git-wiki/sections/content/content.html
_includes/git-wiki/sections/tail/tail.html
_layouts/git-wiki-bs-github.html
_layouts/git-wiki-bs-lux.html
_layouts/git-wiki-bs-united.html
assets/css/github.css

upgraded to 2.3.1

---

docs/FAQ.md

maybe that's kind of duplicate, dunno

Add again bountysource

---

docs/account.md

fix(account): Wrong quotes

---

docs/Installation.md

As suggested the discord user **Stevej**, I put the $HOME variable in the cmake path instead of /home/youruser/ (for Linux and Mac).

Update installation.md, changed cmake PATH adding $HOME variable

---

docs/Extract-Client-Data.md

Extended the How-to guide for Linux and Mac platform

Extended  Extract-Client-Data.md  for Linux and Mac platform

---

docs/smart_scripts.md

- added a comment to "SMART_ACTION_SET_ACTIVE"
- added the AC specific actions 201-217 (216 and 217 are new, see https://github.com/azerothcore/azerothcore-wotlk/pull/1570)

A few updates to the smart scripts documentation

---

docs/Installation.md

Help users understant how to build x32 or x64.

---

docs/achievement_reward.md

Updates the achiement reward wiki for the trinitycore modifications

Achievement Reward update

---

docs/linux-restarter
docs/linux-restarter.md

Adding linux automatic restarter page

Linux automatic restarter page

---

_includes/azerothcore/sidebar.html

Adding linux automatic restarter page

Adding link to Linux automatic restarter in Other:

---

docs/smart_scripts.md

Add documentation for SAI action type "SMART_ACTION_MOVE_FORWARD" (46) which differs from TC (the action doesn't exist there).

Add documentation for SAI action type "SMART_ACTION_MOVE_FORWARD" (46)

---

docs/Bit-and_bytes-tutorial.md

With this document people not familiar with bits or bytes will have a quick sneak peak into bit operations. This will help people understand how to add or remove flags from, for example, spells.
While It doesn't really cover everything in detail, this should suffice for now and can be expanded with more depth eventually.
As mentioned on the description, we will be able to guide people a bit better with spell, npc or state flags.
Doesn't need to be tested since It's only documentation about computing/programming.

[Documentation] Bit operations

---

docs/remove_add_flags.md

Explanation of how to properly query the database to update flags.
Closes #39 
There is a need to explain people how to query the database safely when updating flags for columns.
Doesn't need to be tested.

[Documentation] How to Remove and add flags

---

_includes/azerothcore/sidebar.html

Updated the sidebar of the wiki.
None
Giving more visibility to bit and byte usage

Wiki - Update sidebar

---

docs/item_template.md

Add extra useful information for account bonding

fix: item_template bonding information

---

docs/Dealing-with-SQL-files.md

Improved the page in order to help less experienced developers or new comers to contribute.
No issue reported.
Due to the page missing the small steps and tips, many new comers might feel overwhelmed with how to contribute using this system. I've added some extras that I found crucial to improve the learning experience.
These are the usual steps I take when submitting new pull requests.

fix(Wiki/Documentation): Update Dealing-with-SQL-files

---

docs/item_template.md

feat: Small precision for "unique equipped" flag

---

docs/item_template.md

Verify by doing this and testing items IG:
```sql
SELECT name FROM item_template
WHERE inventorytype = 13
ORDER BY itemlevel DESC
```

fix(item_template): Wrong value for a weapon in inventorytype

---

docs/smart_scripts.md

Added information about the AC specific handling of the action type "SMART_ACTION_MOVE_TO_POS" (46), as it allows to set an additional offset from the target's position.

fix(smart_scripts): Update documentation for SAI action type "SMART_ACTION_MOVE_TO_POS" (46)

---

docs/GM-Commands.md
docs/command.md

Fixed typo in command.md
Added HTML instead of markdown in GM-Commands.md

Fixed typo in previous commits

---

docs/item_template.md

Ddecimal flag error fix for flag 0x02000000
Simple flag info fix

Decimal flag error fix

---

_posts/AzerothCoreHostedTutorial.md

This is a written guide to acompany a video tutorial for setting up AzerothCore on Debian 9.
Setting up an AzerothCore server on a dedicated host can be confusing and hard for someone with little to no Linux background. This guide is a companion to a video tutorial and will walk a user from the very beginning of choosing a VPS configuration all the way through being able to log into the final server.

[Tutorial] AzerothCore on Debian Step-by-Step Guide

---

docs/smart_scripts.md

Updated the smart_scripts documentation in order to reflect the actual state of the implementation in AC. Also added scrollable tables like described in draft PR #90 and updated all links. Hopefully I did not miss anything (the "FactionTemplate" and "Emotes" wiki pages are currently missing, though, see #98).

Update smart_scripts documentation

---

docs/TrinityCore-to-AzerothCore-characters-migration.md

Updated to match pull request https://github.com/azerothcore/tool-tc-migration/pull/5
Updated wiki for new auth converter 
Added new step and renamed to add Auth converter  
https://github.com/azerothcore/tool-tc-migration/pull/5

Update migration tool guide

---

docs/quest_template.md

All those fields have been moved to [quest_template_addon](http://www.azerothcore.org/wiki/quest_template_addon) a long ago (back in TC)

doc: cleanup quest_template (part 1)

---

docs/smart_scripts.md

The action only has 1 parameter, so delete the second.

Fix parameters for SMART_ACTION_SET_INGAME_PHASE_MASK

---

docs/Installation.md
docs/Requirements.md
docs/travis-build.md

Relates to: 
https://github.com/azerothcore/forum/issues/48

update clang version in wiki

---

docs/Installation.md

Added optional user linux creation

Added optional user linux creation

---

_includes/azerothcore/sidebar.html
docs/FAQ.md
docs/Memory-Usage.md
docs/smart_scripts.md

- Add a new page "Memory Usage", containing the text from the FAQ, the minimum requirements depending on the number of players and a recommendation concerning the amount of RAM.
- Remove the text from the FAQ and add a link to the "Memory Usage" page.
- Add a new entry "Memory Usage" to the sidebar.
- Small cosmetic fix concerning the smart_scripts page.

RAM requirements

---

docs/quest_template.md

These fields belong to: http://www.azerothcore.org/wiki/quest_request_items

doc: cleanup quest_template (part 2)

---

docs/Faction.md
docs/gameobject_template.md

Removed useless data that aren't in the 335a gameobject_template table.
Fixed link Faction about gameobject.

Update gameobject_template, close #107

---

docs/creature_template.md

I still need help for the others AI Documentation
Update AIName with all the creature ai existing in the core
I need help so we can have all of them described
https://github.com/azerothcore/wiki/issues/92

AIName completion

---

docs/Database-Setup.md
docs/Environment-Variable.md

Explains how to set-up MySQL.exe as a Environment Variable so Windows users can run db_assembler.sh
Received an issue on discord about this
It solves the problem of beginners with Environment Variables
--
--

MySQL.exe Environment Variable documentation

---

docs/gossip_menu_option.md

Fixed anchor links and converted html table to markdown table in Gossip Menu Option

Fixed anchor links and converted html table to markdown table in Gossip Menu Option

---

docs/creature_template.md

Fixing Creature_Template anchors
https://github.com/azerothcore/wiki/issues/91

Fix for Creature_Template anchors

---

docs/gossip_menu_option.md

Fixed some links in gossip menu option

Fixed some links in gossip menu option

---

docs/conditions.md

see https://github.com/azerothcore/azerothcore-wotlk/pull/2342

Add new condition "CONDITION_QUEST_OBJECTIVE_PROGRESS"

---

docs/GM-Commands.md

Improved markdown table in GM-commands, close https://github.com/azerothcore/wiki/issues/143

Fixed table in GM-commands.md, closes #143

---

docs/GM-Commands.md
docs/World-Database.md
docs/acore_string.md
docs/areatrigger_teleport.md
docs/areatrigger_template.md
docs/areatrigger_template_polygon_vertices.md
docs/broadcast_text.md
docs/creature_template.md
docs/database-world.md
docs/gossip_menu_option.md
docs/item_appearance.md
docs/item_effect.md
docs/item_modified_appearance.md
docs/item_set_names.md
docs/item_sparse.md
docs/npc_text.md
docs/uptime.md

- Align with https://github.com/azerothcore/azerothcore-wotlk/pull/2454
- Some misc cleanups

doc: cleanup trinity_string

---

docs/GM-Commands.md

- restore `GM-Commands.md` as it got reverted in commit 37a67f6
- replace `reload trinity_string` with `reload acore_string`
- remove all trinity* names

restore GM-Commands; add "reload acore_string" command; remove trinity* names

---

docs/FAQ.md
docs/areatrigger_involvedrelation.md
docs/areatrigger_scripts.md
docs/areatrigger_tavern.md
docs/areatrigger_teleport.md
docs/phase_area.md
docs/smart_scripts.md

- smart_scripts:
Remove all entries marked with ❌. They have no functionality in the code and are also not used in the DB (and most likely won't ever be used). Closes #158
- areatrigger:
Use correct links for http://www.azerothcore.org/wiki/DBC-AreaTrigger. Closes #136
- FAQ:
Add information about fixing bugs and exploits even if not blizzlike.

docs: update smart_scripts, areatrigger, FAQ

---

docs/GM-Commands.md

As the PR https://github.com/azerothcore/azerothcore-wotlk/pull/2487 has been merged, update the GM-Commands accordingly.

docs: update GM-Commands

---

docs/creature_template.md

Update AIName for creature_template; closes #92.

docs(creature_template): update AIName

---

docs/digital-ocean-video-tutorial.md

- Updated the initial application install command to add g++-7
- Updated the initial application install command to remove CMake and Make
- Added a section explaining how to install CMake and Make
- Clarified the directions of some parts of the tutorial

DigitalOcean Wiki Updates - CMake, G++7, and other Edits

---

docs/FAQ.md

"I need a new hook for my custom module, what can I do?"

Added new question to FAQ

---

_includes/azerothcore/sidebar.html
docs/Installation.md

Just check the changed file https://github.com/azerothcore/wiki/blob/717bce416432348a4fd1147072cd8c9fad274af6/docs/Installation.md

fix: Small readability improvement on "Installation.md"

---

docs/Installation.md

- Add mega links for latest data files
- Also added a link to DBC and maps that should never/rarely change
- Refactored the section

feat: Add mega links for latest data files

---

docs/linux-restarter.md

- Rewrote the tutorial to make the flow easier to follow
- Used consistent formatting and corrected typos and styling issues
- Added a new script to the guide to allow for single-line termination of the restarters

Rewrote Restarter Script Tutorial

---

README.md

Added documentation to run locally the project.

Added documentation for development

---

docs/conditions.md

Update conditions to match the actual AC implementation of "CONDITION_SOURCE_TYPE_QUEST_ACCEPT" and "CONDITION_SOURCE_TYPE_QUEST_SHOW_MARK".

docs(conditions): Update "CONDITION_SOURCE_TYPE_QUEST_ACCEPT" and "CONDITION_SOURCE_TYPE_QUEST_SHOW_MARK"

---

docs/channels.md

Column not implemented yet in channels.md

---

docs/Bit-and_bytes-tutorial.md

Opening a PR for that so you guys can see what we must do on pages missing titles xD

Add title to bit and bytes

---

docs/arch-linux.md

Added arch-linux.md that explains how to install azerothcore on Arch Linux distribution.

Added installation guide for Arch Linux users

---

docs/loot_template.md

This page is as hard to understand as the system it's describing :'(

fix: Improve loot_template.md

---

docs/how-to-work-with-conf-files.md

- Fixed english
- Added new section "Can I use relative pathes in the configuration files?"
I hope the new section is good and not bad info (I tested this few weeks ago, I did not verify before writing this) and is fitting well in this page (could also put it in the FAQ)

Configuration documentation improved

---

docs/arch-linux.md

update links to azerothcore aur package

update links to azerothcore aur package

---

docs/Requirements.md

Added guide to install the last cmake version on Debian.
Tested on Debian 9.
Thanks [Root#1633](https://github.com/cristian-root)

Add debian cmake installation

---

docs/GM-Commands.md

@Yehonal i don't know how it will look in our wiki because no way to preview it :(
On github it looks like that  (markdown strikethrough):
~~test~~
Note: I didn't remove the .honor update because I don't know if it's implemented or not. In the console it doesn't work, but ingame it returns nothing so I don't know.
closes https://github.com/azerothcore/wiki/issues/181#issuecomment-583887902

fix: Not implemented command

---

docs/achievement_reward.md

style: Improve the text for achievement_reward + fix typos

---

docs/GM-Commands.md
docs/creature.md
docs/creature_template.md
docs/scripts.md

when https://github.com/azerothcore/azerothcore-wotlk/pull/2858 is pushed to core this needs to be pushed to wiki

fix wander_distance

---

docs/smart_scripts.md

https://github.com/azerothcore/azerothcore-wotlk/pull/2878

Add new features & description for SMART_ACTION_SET_IN_COMBAT_WITH_ZONE 

---

docs/smart_scripts.md

https://github.com/azerothcore/azerothcore-wotlk/pull/2881

Implement NEAR_PLAYERS(_NEGATION)

---

docs/smart_scripts.md

Quick implementation of the new SAI Actions from https://github.com/azerothcore/azerothcore-wotlk/commit/8aa80eef181af4babea7dd65b938b5d88de9cd03 since it got pushed today.
It is just a basic implementation and can be improved at another time, but I think it is important that we update the wiki :)

Implement new SAI Actions

---

docs/account.md
docs/account_access.md
docs/account_banned.md
docs/autobroadcast.md
docs/ip2nationCountries.md
docs/logs.md
docs/realmcharacters.md
docs/realmlist.md
docs/uptime.md
docs/version_db_auth.md

TODO: Need to add a ` worldserver.conf` description somewhere since http://www.azerothcore.org/wiki/autobroadcast links to it.

Auth Tables Documentation updates

---

docs/Dealing-with-SQL-files.md

How to remove, add or invert flags in SQL
Might not be put at the right place, dunno, did it in a hurry

feat: Dealing with SQL files and FLAGS

---

docs/spell_group_stack_rules.md

Updating the table of stack rules to match the ones we have in the core.

chore(spell_group_stack_rules): Update the stack rules

---

docs/smart_scripts.md

https://github.com/azerothcore/azerothcore-wotlk/pull/2879
@P-Kito review pls <3

Add from https://github.com/azerothcore/azerothcore-wotlk/pull/2879

---

docs/gm_ticket.md

We should add that option to the core but since nobody gonna do it, i fix the wiki
I wasted 2 hours on this because my queries didn't work (unsigned data type, can't insert -1)

fix: gm_ticket column

---

docs/Update.md

Update to Update.md
Me being a C n00b I tried adding a module and updating my core with the proposed general way first (without re-running cmake) and my module was not being detected and was going back and forth checking what i did wrong or if I put the module incorrectly or if the module was still compatible with this version of AC, went back to the full instructions and saw that maybe i needed to rerun the CMake part, after doing that I saw my module being detected when rebuilding and running my core now. If this line was here it would've save me a bit of time and frustration figuring it out.
Would've saved some time figuring out adding modules when updating your core.

Small update for Update.md

---

docs/conditions.md

These changes need to be pushed to Wiki when https://github.com/azerothcore/azerothcore-wotlk/pull/2859 is pushed to the core.

Fix alignment of CONDITION_SOURCE_TYPE_QUEST_AVAILABLE

---

docs/item_template.md

Just read what I proposed, it's interesting!
Finally this system is now explained to everybody xD

fix: item_template bonding to account explained to dummies

---

docs/smart_scripts.md

Just a refactor from HTML to markdown, a bit annoying to do but doable
i used this https://www.tablesgenerator.com/markdown_tables and also i used my text manipulation skills to do it ^^
this is just a test and to show people how we can do it

refactor: smart_scripts table

---

docs/npc_vendor.md

- Add info about GM mode that I just discovered
- Fix links
- Remake html table into markdown for maintanability

refactor: npc_vendor table html to markdown + extra info

---

docs/Installation.md

https://github.com/azerothcore/azerothcore-wotlk/pull/3104#issuecomment-636908822

fix: installation cmake command

---

docs/item_template.md

I found this by testing ingame

fix: item_template info about Map & Area

---

docs/creature_template.md

inhabittype 8 doesn't exist
I can't preview how it looks

fix: creature_template non implemented option

---

docs/item_template.md

Close https://github.com/azerothcore/wiki/issues/241

chore(item-template): add ItemLimitCategory desc

---

docs/npc_text.md

God this page is ugly as fuck, everything is repeated 150 times

fix: Add explanation for language to npc_text

---

_includes/azerothcore/sidebar.html
docs/bash_system.md
docs/documentation_index.md
wiki/main_page.md

Since our documentation is growing, the sidebar is starting to be too big and maybe a dedicated documentation index page can be more readable and easier to maintain

Bash system + documentation index

---

docs/account.md

- Before that commit, it was missing the column "totaltime" which was added by Nefertumm or Winfi on my behalf xD
Note that i'm only 99% sure that it stores the time for deleted characters as it was one of the thing that bothered me when I asked the dev to code it. But if someone wants to verify
- Refactored the table, now it's perfect

refactor: account table now in markdown + add "totaltime"

---

docs/gm_ticket.md

fix: Add bit more info to gm_ticket

---

docs/lag_reports.md

- Add data for lagtype
- Add two missing columns
- Refactor that page to correct markdown

refactor: lag_reports.md markdown table + add missing columns

---

docs/gm_subsurvey.md

fix: gm_subsurvey not implemented

---

docs/characters.md

- Added the max length for character name
- Refactored all the markdown tables to be easily maintanable
- Fixed small quirks
- Improved indentation

refactor: characters.md code improved

---

docs/Requirements.md

There should be only 1 main title per page, which is the page's title.
Otherwise the page takes the first main title:
which is wrong

doc(Requirements): fix titles

---

docs/Installation.md

Removing the command character. A simple typing error.
Thank you **CyberFox#1701** for mentioning it in discord.

Typing error.

---

docs/Database-Setup.md
docs/digital-ocean-video-tutorial.md

Documentation for: https://github.com/azerothcore/azerothcore-wotlk/pull/3259

doc: for feature/bash-support-derivated-distro

---

docs/unit-testing.md

Documentation for: https://github.com/azerothcore/azerothcore-wotlk/pull/3273

doc: create unit-testing

---

docs/playercreateinfo_item.md

https://github.com/azerothcore/azerothcore-wotlk/pull/3122

chore(playercreateinfo_item): Update with master

---

docs/access_requirement.md

@BarbzYHOOL is having issues with github + requested that someone create a pull request with the changes they wanted to make. See #279 for more information.

Access_Requirement: Add a few useful notes + typo fixes

---

docs/Requirements.md

Should point to the latest MySQL, not to 5.6

fix(installation): Windows' MySQL download link

---

docs/How-to-create-a-PR.md

No longer forced to use VIM which is user unfriendly

fix: how to make a PR with NANO

---

docs/unit-testing.md

Align with: https://github.com/azerothcore/azerothcore-wotlk/pull/3809

docs: align test build

---

docs/instance_template.md

fix: instance_template allowMount

---

docs/How-to-ask-for-help.md

- Make it shorter
- Add github login

docs: make How-to-ask-for-help shorter and add github login

---

docs/Database-Setup.md

How to create the acore user manually

---

docs/spell_proc_event.md

chore(spell_proc_event): Add definitions

---

docs/item_template.md

fix: Useful info about spell cooldowns in item_template

---

docs/Installation.md

chore(Installation.md): Update build shortcut

---

docs/Extract-Client-Data.md

Small changes to the guide so it can be easier for users
Users are composed of a diverse type of people, the easier the guide is to read and follow the better, this can help non-techy people to use this tool appropriately.

chore(docs/ExtractClientData): Update for mapextractor guideline

---

docs/achievement_reward_locale.md

The structure was modified
Information about the fields has been added.

Updating structure and data of `achievement_reward_locale`

---

docs/achievement_reward_locale.md

I add an example of an SQL on achievement 13 in Spanish.

SQL example of a Spanish translation.

---

docs/Installation.md

chore(Installation): Update mysql path

---

docs/quest_mail_sender.md

Information about the missing file is added.

Adding the `quest_mail_sender` table

---

docs/quest_offer_reward_locale.md

Documentation is added to the table

Adding the `quest_offer_reward_locale` table

---

docs/TotemCategory.md
docs/character_inventory.md
docs/character_reputation.md
docs/disables.md
docs/item_sparse.md
docs/npc_spellclick_spells.md
docs/playercreateinfo_action.md
docs/quest_poi_points.md
docs/vehicle_accessory.md
docs/vehicle_template_accessory.md

Continuing the conversion
https://github.com/azerothcore/wiki/issues/247
https://github.com/azerothcore/wiki/search?q=%3Ctbody%3E
https://jmalarcon.github.io/markdowntables/
https://www.tablesgenerator.com/markdown_tables

Converting from HTML to Markdown part #2

---

docs/achievement_dbc.md
docs/areatrigger_scripts.md
docs/areatrigger_tavern.md
docs/areatrigger_template_actions.md
docs/battlemaster_entry.md
docs/character_battleground_random.md
docs/character_queststatus_weekly.md
docs/creature_onkill_reputation.md
docs/creature_questender.md
docs/creature_queststarter.md
docs/exploration_basexp.md
docs/game_event_arena_seasons.md
docs/game_event_gameobject.md
docs/game_event_save.md
docs/game_graveyard_zone.md
docs/gameobject_queststarter.md
docs/group_instance.md
docs/guild_rank.md
docs/item_loot_money.md
docs/item_template.md
docs/lfg_data.md
docs/lfg_dungeon_encounters.md
docs/mail.md
docs/outdoorpvp_template.md
docs/player_xp_for_level.md
docs/pool_quest_save.md
docs/realmlist.md
docs/skill_fishing_base_level.md
docs/spell_proc.md
docs/spell_threat.md

The idea of the pull request, is to replace the tables written in HTML, and convert them to markdown format. Links are also created to the attributes, so that they can be accessed, from the table.
https://github.com/azerothcore/wiki/issues/247
https://github.com/azerothcore/wiki/search?q=%3Ctbody%3E
https://jmalarcon.github.io/markdowntables/
https://www.tablesgenerator.com/markdown_tables

Converting from HTML to Markdown part #3

---

docs/UpdateFields.md

A missing file is incorporated.
https://github.com/azerothcore/wiki/issues/280

Creating UpdateFields.md file

---

docs/Installation.md

Adding information in Installation

---

docs/quest_template_locale.md

We updated the table attributes and added an example in SQL of a Spanish translation.
- https://github.com/azerothcore/wiki/issues/289

Updating `quest_template_locale`

---

docs/quest_request_items_locale.md

Adding table that does not exist.

Adding the `quest_request_items_locale` table

---

docs/logs_ip_actions.md

Review and update the information in the auth database
https://github.com/azerothcore/wiki/issues/338

Creating logs_ip_actions.md

---

_includes/azerothcore/sidebar.html
docs/How-to-obtain-free-records.md

The idea is to explain how to find free records within a table.

How-to-obtain-free-records.md

---

docs/Database-Setup.md

- Removing some lines
- Adding SQL syntax to highlight the code
- Closes

Adding SQL syntax in Database-Setup

---

docs/database-auth.md

The idea is to update the current information a little bit.
- Closes

Modifying information in database-auth

---

docs/linux-restarter.md

Simply added the sh, so the code can be highlighted and some line breaks, to make it a little more spaced.
- Closes

Adding sh syntax in linux-restarter

---

docs/database-world.md

The text of database-world is updated
https://github.com/azerothcore/wiki/issues/357

Review and update database world

---

docs/access_requirement.md

The information in the table was updated, and 2 sample records were added at the end.
https://github.com/azerothcore/wiki/issues/357

Review and update: access_requirement

---

docs/areatrigger_involvedrelation.md

Revise the structure and accommodate the document.
https://github.com/azerothcore/wiki/issues/357

Adding examples in areatrigger_involvedrelation

---

docs/How-to-obtain-free-records.md

Fixing an aesthetic detail in SQL

---

docs/Requirements.md

Shell Script Syntax.
Some additional information.

Syntax arrangement and some information

---

_layouts/azerothcore.html

Revert "chore(azerothcore.html): Stop the wiki for generating table of contents"

---

docs/game_graveyard_zone.md

fix(graveyard): little typo

---

docs/chrclasses.md

Missing file is added.
https://github.com/azerothcore/wiki/issues/388

Adding ChrClasses file

---

docs/creature_template.md

to be merged alongside https://github.com/azerothcore/azerothcore-wotlk/pull/4358/

chore(c_t): Add spell_school_immune_mask

---

docs/GM-Commands.md

- Most of command security level of https://www.azerothcore.org/wiki/GM-Commands was completely wrong
- Related to: https://github.com/azerothcore/azerothcore-wotlk/pull/4479

docs(GM-Commands): align with core

---

docs/chrraces.md

feat: Add faction value to chrraces

---

_layouts/azerothcore.html

We added a variable, in order to disable the content, in some pages.
https://github.com/azerothcore/wiki/issues/267

custom variable in azerothcore.html

---

docs/creature_template.md
docs/creature_template_resistance.md
docs/creature_template_spell.md
docs/database-world.md

to be merged alongside https://github.com/azerothcore/azerothcore-wotlk/pull/4359

chore(c_t): Add c_t_r & c_t_s

---

docs/Contribute.md

chore(Wiki): Fix typo on "How to create a Pull Request"

---

docs/Requirements.md

https://github.com/azerothcore/azerothcore-wotlk/pull/5082

Requirements: set min require CMake to 3.16

---

docs/Requirements.md

Update Cmake minimum version (3.6)

chore(Wiki): Update Cmake minimum version [3.16]

---

docs/creature_formations.md

- Remove attachment section
- Add better description on memberGUID (waste 6 hours because the lack of this explanation)
- Make an example of how leaderGUID and memberGUID would work
- Delete duplicated text

fix(Wiki): Improve creature_formations

---

docs/GM-Commands.md

This command is actually level 2. Changing to align it to the core.

fix(GM commands): reflect actual level

---

docs/Install-with-Docker.md

Needed after https://github.com/azerothcore/azerothcore-wotlk/pull/4488

Updated installation guide after the docker PR

---

docs/database-only-quick-setup.md

After latest changes made to the docker system, you need to run another command to create and update the database

Fix database-only guide

---

docs/account.md

chore(account): Update to latest master

---

docs/transports.md

chore(transports): Update to wiki standards

---

docs/logs.md

- Update info after new logging system
-

chore(Auth/Logs): update logging info

---

docs/database-characters.md
docs/recovery_item.md

closes https://github.com/azerothcore/wiki/issues/442

chore(docs): Basic implement of recovery_item

---

docs/Install-with-Docker.md

Simple instructions for adding a module while using docker containers for AzerothCore + where to place configuration files.
Fixes https://github.com/azerothcore/wiki/issues/276
Follows up on https://github.com/azerothcore/wiki/pull/436 but uses the latest documentation.
A simple but useful addition, especially since it also tells you where to place the configuration files.

Updates more info section with a how to install modules section

---

docs/gameobject_addon.md

closes https://github.com/azerothcore/wiki/issues/475

chore(gameobject_addon): Some info

---

docs/creature_text_locale.md

The table attributes were out of date.
https://github.com/azerothcore/wiki/issues/467

Updating creature_text_locale attributes

---

docs/linux-requirements.md

- https://github.com/azerothcore/azerothcore-wotlk/pull/5671

chore(Requirements): update min versions compiler for linux os

---

docs/linux-requirements.md
docs/macos-requirements.md
docs/windows-requirements.md

- https://github.com/azerothcore/azerothcore-wotlk/pull/5676

feat(Requirements/Boost): added boost support

---

docs/How-to-test-a-PR.md

This should help newer users who are still unsure of the PR process to revert changes made after testing a PR.
Note - I'm not knowledgeable with git and there are probably better ways to do this. Any improvements welcome.
N/A.
For new users, who are working their way through the PR process, git is also confusing, so showing how to revert changes easily should be useful.

Suggestion: Added info on reverting PRs once finished testing

---

docs/quest_template.md

update some field names (related https://github.com/azerothcore/azerothcore-wotlk/pull/300 )

chore: update name fields

---

docs/es/account_access.md

Testing if the translations work.
- closed
Translate documentation into Spanish.

Translation of the document account_access.md

---

_config.yml

Revert "chore: Test if this fixes some stuff"

---

_config.yml

Created permalink for the /docs/es folder in order to show the files of that directory

Permalink for docs/es/ folder

---

docs/server-setup.md

chore: No instant download, that's annoying

---

docs/es/account_access.md

Testing if the translations work.
- https://github.com/azerothcore/wiki/issues/539
Translate documentation into Spanish.

chore: Translation of the document account_access.md

---

docs/es/account_access.md

- Removing permalink in account_access
Have the wiki translated into several languages.

removing permalink in account_access

---

docs/installation.md

The bold makes it hard to see that it is a link on the wiki.
Make it more clear for which os this guide works on

chore: installation

---

docs/account.md

Updates of the Wiki files in English

updates of the wiki files in English

---

docs/database-installation.md
docs/database-keeping-the-server-up-to-date.md

chore: automatic db updater

---

docs/es/account.md
docs/es/arch-linux.md
docs/es/aws-tutorial.md
docs/es/bash_system.md
docs/es/best-practices.md
docs/es/bit-and-bytes-tutorial.md
docs/es/bountysource.md
docs/es/contribute.md
docs/es/core-installation.md
docs/es/faq.md
docs/es/file-headers.md
docs/es/home.md
docs/es/how-to-debug.md
docs/es/importing-spell-dbc.md
docs/es/keeping-the-server-up-to-date.md
docs/es/trinitycore-to-azerothcore-characters-migration.md
docs/es/upgrade-from-pre-2.0.0-to-latest-master.md
docs/es/upgrade-from-pre-3.0.0-to-latest-master.md
docs/es/wiki-standards.md

Updates and creation of wiki files in Spanish #539

Updates and creation of wiki files in Spanish

---

docs/es/account_access.md
docs/es/database-auth.md
docs/es/ip_banned.md
docs/es/logs.md
docs/es/logs_ip_actions.md
docs/es/realmcharacters.md
docs/es/realmlist.md
docs/es/secret_digest.md
docs/es/update.md
docs/es/updates_include.md
docs/es/uptime.md
docs/es/version_db_auth.md

Updates and Creation of the wiki files in Spanish (auth)

---

_config.yml

It's actually good, lol
You can test it here https://cse.google.com/cse?cx=3211b10d74ee61986

chore: update search to google

---

_config.yml

Revert "chore: update search to google"

---

docs/es/home.md
docs/home.md

**A simple change to be able to read the documents to the preference of the users**
Read in: [English :gb:](home) [Spanish :es:](es/home)
Leer en: [English :gb:](home) [Spanish :es:](es/home)
`Read in: [English :gb:](home) [Spanish :es:](es/home)`
@Kitzunu @Helias

Language changes for documents

---

docs/es/account.md
docs/es/account_access.md
docs/es/account_banned.md
docs/es/account_muted.md
docs/es/autobroadcast.md
docs/es/build_info.md
docs/es/database-auth.md
docs/es/ip_banned.md
docs/es/logs.md
docs/es/logs_ip_actions.md
docs/es/realmcharacters.md
docs/es/realmlist.md
docs/es/secret_digest.md
docs/es/uptime.md
docs/es/version_db_auth.md

Update Auth ES
* Language change
* Table structures
* Code standards

Update db-auth Es

---

docs/ac-dashboard-core-installation.md

this would have saved me 30 minutes time

docs: explicitely tell how to access mysql for the first time

---

docs/es/home.md

Fix Update the links to change the language from Spanish to English   #599

Update the link es-to-en for es/home.md

---

useful-sql.md

Adds a quick reference SQL snippets page for triagers.

Adds 'Useful SQL Snippets' Page

---

docs/useful-sql.md

Adds another query to the list for finding respawn timers for a class of game object, and fixes a broken link.

Add respawn timer query

---

docs/documentation-index.md

Adds the Useful SQL Snippets page link to the "Recipes and Techniques" section of the Documentation index. It's not important enough to be on the sidebar or anything, this seems like a decent spot for it.

Adds Useful SQL link to Documentation index

---

_includes/azerothcore/sidebar.html

Adds a link to the bug triaging guide to the wiki sidebar under the 'Contribute' heading.

Add link to triaging guide to the sidebar

---

docs/server-setup.md

chore: update server-setup.md

---

docs/creating-accounts.md

Fix field name of account table.

fix: typo 'name' to 'username'

---

docs/guide-to-triaging.md

Remove the ToC as it wasn't working and didn't seem particularly necessary.

Remove ToC

---

docs/useful-sql.md

Corrects a query so it gives proper output, not just an item name.

Fix RLT query in Useful SQL Snippets page

---

docs/documentation-index.md
docs/how-to-use-gperftool.md

Documentation for this old PR: https://github.com/azerothcore/azerothcore-wotlk/pull/5769

doc: how to use gperftool

---

docs/macos-requirements.md

update command `brew install --cask`

fix: macos-requirements.md

---

docs/how-to-restart-and-debug.md

Update info about debugger.
Closes

Update restarter/debugger wiki

---

docs/creature_addon.md

chore: update creature_addon

---

docs/bit-and-bytes-tutorial.md

I knew some people that didn't like bitmask and so, but this is another level of hate... 🤣 Just fix the typo, the guy who wrote this __clearly__ wanted to type *shift*
Closes

Fix bits and bytes tutorial typo

---

docs/es/requirements.md

The requirements.md document is created in Spanish so that the entire Spanish-speaking community can enjoy this wonderful document.

I add Spanish translation of requirements.md

---

docs/linux-requirements.md

chore: MariaDB

---

docs/es/documentation-index.md
docs/es/installation.md
docs/es/server-setup.md

server-setup.md translation into Spanish

Server setup translation into Spanish

---

docs/macos-core-installation.md
docs/macos-requirements.md

macos pin openssl to 1.1 
Closes

fix: macos pin openssl to 1.1

---

docs/keira3-internals.md

ref https://github.com/azerothcore/Keira3/pull/1583

fix(keira3-internals/e2e): replace Spectron with Playwright

---

docs/mail.md

extend description of expire_time

Extend description for expire_time field

---

docs/mail.md

Description of auctionId field

Added Description of auctionId field

---

docs/mail.md

Additional description about formatted Subject and Body
Taken from AuctionHouseMgr.cpp
AuctionEntry::BuildAuctionMailSubject
AuctionEntry::BuildAuctionMailBody

characters.mail table : description about formatted data in Subject and Body fields

---

docs/es/ac-dashboard-core-installation.md
docs/es/account.md
docs/es/account_access.md
docs/es/account_banned.md
docs/es/account_data.md
docs/es/account_instance_times.md
docs/es/account_muted.md
docs/es/account_tutorial.md
docs/es/achievement.md
docs/es/achievement_criteria.md
docs/es/achievement_criteria_data.md
docs/es/achievement_dbc.md
docs/es/achievement_reward.md
docs/es/client-setup.md
docs/es/common-errors.md
docs/es/database-installation.md
docs/es/final-server-steps.md
docs/es/how-to-ask-for-help.md
docs/es/linux-core-installation.md
docs/es/networking.md
docs/es/wiki-standards.md
docs/es/windows-core-installation.md
docs/es/windows-keeping-the-server-up-to-date.md
docs/es/windows-requirements.md
docs/es/windows-server-setup.md

Updates, fixes, and new translations into Spanish of some wiki files.

Updates, fixes, new translations into Spanish.

---

docs/common-errors.md

Make ACE00023 more user friendly

---

docs/creature_template.md

chore: swim and flight speeds

---

docs/server-setup.md

Swaps out old version number and date released with most recent release.
Closes

Correct data.zip version number and date.

---

docs/contribute.md

Some of the links at the top of the Contribute page were broken so I have updated them.

Update links to contribution guides

---

docs/es/keira3-internals.md

The idea was simply to be able to translate the document, since my intention is to learn a little more about the project, as well as the technologies mentioned here. I hope that this document will help more people to understand the structure and operation of this tool, and collaborate in its development.
Closes

Spanish translation by keira3-internals

---

docs/ac-dashboard-core-installation.md

Remove DB-assembler from dashboard guide
Closes

chore: remove db-assembler

---

docs/es/server-setup.md
docs/server-setup.md

Update server setup

---

docs/database-world.md
docs/quest_greeting.md
docs/quest_greeting_locale.md

https://github.com/azerothcore/azerothcore-wotlk/pull/10526

chore: quest_greeting

---

docs/installation.md

To be merged with https://github.com/azerothcore/azerothcore-wotlk/pull/11002
Recommend the dashboard for Mac OS system too
Closes https://github.com/azerothcore/wiki/issues/653

chore: add dashboard recommended for Mac OS

---

docs/es/how-to-create-a-pr.md

This is the translation of the document how-to-create-a-pr.md to the Spanish language
(https://github.com/azerothcore/wiki/issues/539)

Added the Spanish translation of how-to-create-a-pr.md

---

docs/es/linux-requirements.md

I create the document linux-requirements to the folder 'es' for the translation of the corresponding section in the wiki.

Added Spanish translation for linux-requirements.md

---

docs/es/how-to-create-a-db-pr.md

I create the document how-to-create-a-db-pr to the folder 'es' for the translation of the corresponding section in the wiki.

Added Spanish translation for how-to-create-a-db-pr.md

---

docs/es/macos-requirements.md

I create the document 'macos-requirements' to the folder 'es' for the translation of the corresponding section in the wiki.

Added Spanish translation for macos-requirements.md

---

docs/worldstates.md

Fixed typos, added wiki quest links and quest=id### next to wiki quest links.
Closes

Fixed typos and wiki links.

---

docs/server-setup.md

Updates the data.zip link info to reflect recent update.
Closes

Updata data.zip version number and date for v14.

---

docs/chrclasses.md
docs/chrraces.md

Includes more info on fields and removes info that doesn't pertain to 3.3.5a.
Closes

Update chrraces.md and chrclasses.md

---

_includes/azerothcore/sidebar.html
docs/achievement.md
docs/achievement_criteria.md
docs/areatable.md
docs/chrclasses.md
docs/chrraces.md
docs/dbc-areatrigger.md
docs/dbc-index.md
docs/documentation-index.md
docs/emotes.md
docs/faction.md
docs/factiontemplate.md
docs/holidays.md
docs/languages.md
docs/map.md
docs/pagetextmaterial.md
docs/skillline.md
docs/spell.md
docs/totemcategory.md

Creates a page to put all the DBC pages together in a manner similar to the database pages. Also add links to the DBC pages to go back to the DBC index page.
Closes

Add DBC index page

---

docs/server-setup.md

Update full data version number

---

docs/windows-core-installation.md

Typo in windows-core-installation.md

---

docs/server-setup.md

Server-setup.md wiki clearifications

---

docs/linux-core-installation.md

This is so modules compile properly.
Closes

Update linux-core-installation cmake instructions

---

docs/windows-requirements.md

Replaces Git Extensions link that went to sourceforge project to the current project maintained on Github.
Whoops.

Update Git Extensions to current version.

---

docs/server-setup.md

It's that time of year again :D
Update maps version to reflect recent change.

Update maps version in server-setup.md

---

docs/sniffing-and-parsing.md

This corrects `durning` to `during`.
N/A

spelling error in sniffing-and-parsing.md

---

docs/es/create-a-module.md

The create-a-module file is added in Spanish.

Add (Translation\ES): create-a-module file in Spanish

---

docs/es/home.md

I have not yet added information on the use of OpenSSL.
Closes

Edit (Translation\ES): Update home.md

---

docs/es/linux-restarter.md

The Linux reboot document is created in Spanish.

Add (Translation\ES): linux-restarter file in Spanish

---

.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/general.md

The idea is to replace the feature_request, for a form that is a little more intuitive, where people are requested, the information we want to collect, and thus, ensure that the fields are completed with the necessary information.
Closes

Replace feature_request.md file with feature_request.yml file

---

docs/es/external-tools-and-modules.md
docs/external-tools-and-modules.md

A title is created within both documents and translated into Spanish.

Add (Translation\ES): external-tools-and-modules

---

docs/creating-accounts.md
docs/es/creating-accounts.md

The account creation page is translated, and examples are added to both pages.

Add (Translation\ES): creating-accounts.md

---

docs/es/how-to-obtain-free-records.md
docs/how-to-obtain-free-records.md

The document is added in Spanish, and a note is added to explain that at this moment, record 15 is occupied, but the method is still valid. The difference is that instead of getting the `guid` 15, you may get a higher one.

Add (Translation\ES): how-to-obtain-free-records

---

docs/create-a-script.md
docs/es/create-a-script.md

The document in Spanish is added, and the structure of the document is slightly adjusted. A missing link to the creation of modules in both files is also added.

Add (Translation\ES): create-a-script

---

docs/es/how-to-obtain-free-records.md

When I tried to enter the page, I noticed that it kept redirecting, so surely, the problem is that line that I am trying to eliminate in this PR.
Closes

Update (Translation\ES): how-to-obtain-free-records

---

docs/es/how-to-test-db-only-changes.md

The translation of the file into Spanish is added.

Add (Translation\ES): how-to-test-db-only-changes.md

---

docs/es/how-to-test-db-only-changes.md

When adding the document, I added those lines to the beginning of the document to test if the URL restructuring worked, but it did not. It is necessary to delete these lines, so that the document is found.
Closes

Update (Translation\ES): how-to-test-db-only-changes

---

docs/es/how-to-document-code.md
docs/how-to-document-code.md

The Spanish document has been added, and a link in both documents has been corrected. Unnecessary lines have also been eliminated.

Add (Translation\ES): how-to-document-code

---

docs/es/how-to-test-a-pr.md

A Spanish translation of the document is added.

Add (Translation\ES): how-to-test-a-pr

---

docs/es/guide-to-triaging.md

The document is added to Spanish.

Add (Translation\ES): guide-to-triaging

---

docs/es/database-characters.md

Add (Translation\ES): database-characters

---

docs/es/remote-access.md

Add (Translation\ES): remote-access

---

docs/es/how-to-work-with-conf-files.md

Add (Translation\ES): how-to-work-with-conf-files

---

docs/create-a-script.md
docs/es/create-a-script.md

The document is inaccessible, because it is being redirected all the time.
Closes

Update (Translation\ES): create-a-script

---

docs/es/standard-operating-procedure.md

Add (Translation\ES): standard-operating-procedure

---

docs/es/hooks-script.md

The translation of the document into Spanish is added.

Add (Translation\ES): hooks-script

---

_includes/azerothcore/sidebar.html

The idea is that the language is changed based on a URL parameter. That way, we will be able to maintain the language of the sidebar, even if we change the page within the wiki. If it has the 'es', the sidebar is shown in Spanish, and if it has nothing, or another language, the sidebar is shown in English.
**English:**
**Spanish**
Closes

Update (Translation) sidebar language change

---

docs/es/hooks-script.md
docs/hooks-script.md

I also took advantage of the opportunity to eliminate some spaces in the Spanish document, and in the English document, I also took advantage of the opportunity to eliminate some spaces and to arrange the functions a little bit.
Closes

Update (Translation\ES): hooks-script

---

docs/es/sql-versioning.md
docs/sql-versioning.md

I create the document in Spanish, and make some modifications in both. Although this method, currently I think it is no longer applicable, because I have seen that the script was modified, anyway, it is part of the documentation and needs to be added. Then in any case, it can be updated later.

Add/Update (Translation/ES) sql-versioning

---

docs/es/core-scripts.md

Add (Translation/ES) core-scripts

---

docs/es/changelog.md

Add the changelog file in Spanish.

Add (Translation\ES) changelog

---

docs/es/directory-structure.md

The document is added to Spanish.

Add (Translation/ES) directory-structure

---

docs/es/cmake-options.md

Add (Translation/ES) cmake-options

---

docs/es/exitcodes.md

The document is added to the Spanish version

Add (Translation/ES) exitcodes

---

docs/es/documentation-index.md

We updated the file, in order to remove / include missing links.

Update (Translation/ES) documentation-index

---

docs/es/how-to-restart-and-debug.md
docs/how-to-restart-and-debug.md

We create the document in Spanish, and add the title in both documents.

Add/Update (Translation/ES) how-to-restart-and-debug

---

PULL_REQUEST_TEMPLATE.md

The structure of the file has been modified to add links to Spanish and a few words of thanks to the contributors. Also, a message is left, that if you need to make an update in the page or creation in Spanish of the same, please tag @pangolp so he can make such update.
Closes

Update (Github/PR) pull_request_template.md

---

docs/es/character_pet_declinedname.md
docs/es/character_queststatus.md
docs/es/character_reputation.md
docs/es/character_skills.md
docs/es/character_social.md
docs/es/character_spell_cooldown.md
docs/es/characters.md
docs/es/gm_ticket.md
docs/es/instance.md
docs/es/mail_server_character.md
docs/es/mail_server_template.md
docs/es/pvpstats_battlegrounds.md

- Adds spanish translations of the characters table
Closes

Some spanish translations

---

docs/es/character_stats.md
docs/es/creature_respawn.md
docs/es/gameobject_respawn.md
docs/es/gm_survey.md
docs/es/group_member.md
docs/es/groups.md
docs/es/guild.md
docs/es/guild_bank_item.md
docs/es/guild_bank_right.md
docs/es/guild_bank_tab.md
docs/es/guild_eventlog.md
docs/es/guild_member.md
docs/es/guild_member_withdraw.md
docs/es/guild_rank.md
docs/es/instance_reset.md
docs/es/item_instance.md
docs/es/item_refund_instance.md
docs/es/lag_reports.md
docs/es/log_arena_fights.md

- Adds spanish translations from the english characters table
Closes

Add (Translation/ES) Translations in characters

---

docs/es/character_account_data.md
docs/es/character_achievement.md
docs/es/character_arena_stats.md
docs/es/character_banned.md
docs/es/character_declinedname.md
docs/es/character_entry_point.md
docs/es/character_glyphs.md
docs/es/character_homebind.md
docs/es/character_instance.md

- Adds spanish translations from the english characters table
- Final translations of the characters table
Closes

Add (Translation/ES) Translations in characters 

---

docs/achievement_criteria.md
docs/es/achievement.md
docs/es/achievement_criteria.md
docs/es/dbc-index.md
docs/es/documentation-index.md

- Create the dbc-index.md table in spanish, update information achievement_criteria.md (english) and updates information in some '.md' tables (spanish).
Closes

Add/Update (Translation/ES) and achievement_criteria.md (EN)

---

docs/es/achievement.md

- Update spanish achievement.md table
Closes

Update (Translation/ES) achievement.md

---

docs/es/instance_enchantments.md
docs/es/item_instance.md

- Translate: https://github.com/azerothcore/wiki/pull/802
Closes

Add/Update (Translation/ES) Instance_enchantments.md and Item_instance.md

---

docs/es/remote-access.md
docs/remote-access.md

- Updates remote-access hyperlink to reflect new location of worldserver.conf.dist.

Update remote-access.md hyperlink.

---

docs/installation.md

- changes the Docker guide description to be in line with what the support is like on our Discord.
- 
Closes

Docker installation recommendation change

---

docs/creature_formations.md

- Adds new flag 0x008 to the creature_formations GroupAI table
- Flag was implemented here https://github.com/azerothcore/azerothcore-wotlk/pull/11512
Closes

Update creature_formations GroupAI to include new flag

---

docs/windows-requirements.md

- Updates Boost version from 1.74, 14.2 to 1.74, 14.3.

chore: Update Boost download version

---

docs/windows-requirements.md

- Updates Boost download link to more recent version.

Replace Boost version in Windows Requirements to (existing) 1.79.0

---

docs/linux-requirements.md

- https://github.com/azerothcore/azerothcore-wotlk/pull/13354

Update linux-requirements for OpenSSL 3

---

docs/windows-requirements.md

- https://github.com/azerothcore/azerothcore-wotlk/pull/13354

Update windows-requirements for OpenSSL 3

---

docs/windows-core-installation.md

- https://github.com/azerothcore/azerothcore-wotlk/pull/13354

Update windows-core-installation for OpenSSL 3

---

docs/linux-requirements.md

Revert "Update linux-requirements for OpenSSL 3"

---

docs/windows-core-installation.md

Revert "Update windows-core-installation for OpenSSL 3"

---

docs/windows-requirements.md

Revert "Update windows-requirements for OpenSSL 3"

---

docs/windows-core-installation.md

- Changes wording from a checkbox to a multiple choice selection.

Update Windows installation to more accurately reflect CMake steps.

---

docs/es/chrclasses.md
docs/es/chrraces.md
docs/es/holidays.md
docs/es/languages.md
docs/es/pagetextmaterial.md
docs/es/skillline.md
docs/es/spell.md
docs/es/totemcategory.md

- Adds the latest translations needed to complete DBC Index
- 
Closes

Add (translation/ES) Spanish translations in the DBC Index

---

docs/gameobject.md

- What the title says, because I couldn't find it when searching around and found out when trying it myself
- 
Closes

Add gameobject respawn behaviour description when spawntimesecs is set to 0

---

docs/cpp-code-standards.md

- Replaces `conding` with `coding`.

Correct spelling error in cpp-code-standards.md.

---

docs/linux-requirements.md

Revert "Revert "Update linux-requirements for OpenSSL 3""

---

docs/windows-core-installation.md

Revert "Revert "Update windows-core-installation for OpenSSL 3""

---

docs/windows-requirements.md

Revert "Revert "Update windows-requirements for OpenSSL 3""

---

docs/windows-core-installation.md

- Changes 'leagacy.dll' to 'legacy.dll'

Correct typo in Windows Core Installation.

---

docs/how-to-restart-and-debug.md

- Mostly just general grammatical and consistency changes.

Fix a bunch of small things with how-to-restart-and-debug.

---

docs/server-setup.md

Feat: Update wiki for new data release

---

docs/sql-standards.md

You didn't see the typo
Closes

Adds details for better DELETE queries in sql-standards.md

---

docs/windows-requirements.md

- Updates minimum Boost version to the earliest with an existing version for Visual Studio 17 (2022).
- Updates Boost download hyperlinks to the latest available.
- Changes the example Boost directory to a likely default.

Update some Boost version numbers/download links.

---

docs/networking.md

- Adds that a fqdn can be used to the `acore_auth` database's address column
- Expand desc for Public IP that the installation guide can't properly instruct the reader on how to set up port forwards
N/A

 Add domain names to networking documentation 

---

docs/documentation-index.md
docs/how-to-use-warden-payload-mgr.md

There should be some documentation on this as it's a little complicated at first.
This PR should be held when until [PR on azerothcore](https://github.com/azerothcore/azerothcore-wotlk/pull/14723) gets merged.
Closes nothing

Add a page for the Warden Payload Manager

---

docs/macos-core-installation.md

Also streamline the usage of nproc in the commands

macos-core-installation.md: Fix paths for brew packages

---

docs/sql-standards.md

- Clarification that was noted in https://github.com/azerothcore/azerothcore-wotlk/pull/15201
Some people might not use the standard database names
None previously created

Explicitly exclude database name in queries

---

docs/command.md

- Creates a link to the breakdown of the commands table within the table explanation.
Closes

add link to commands breakdown page

---

docs/conditions.md
docs/playercreateinfo_skills.md
docs/playercreateinfo_spell_custom.md
docs/quest_template_addon.md
docs/spell_area.md

And few other places as well.
Closes none

Update unlinked chrraces and chrclasses.

---

docs/loot_template.md

group 0 does not apply, so added >0
- 
- 
Closes

added clarity to groupID definition

---

docs/cpp-code-standards.md

CPP Standards: No php style brackets

---

docs/windows-core-installation.mdg
docs/windows-requirements.md

Revamp windows install guide

---

docs/windows-requirements.md

Spell error in doc.

---

docs/aws-tutorial.md
docs/digital-ocean-video-tutorial.md
docs/how-to-create-a-pr.md
docs/how-to-document-code.md
docs/installing-a-module.md
docs/windows-requirements.md

Fixed typos

---

docs/waypoints-information.md

- Change 'pathes' to 'paths' in the waypoints information document.

Correct typo.

---

docs/server-setup.md
docs/windows-server-setup.md

-  fixes the old path names to the current path names. Dunno when this changed, but now it should fit when you reinstall azerothcore
Closes no reported issue

fix: update data folder paths for windows and linux

---

docs/install-with-docker.md

- Small note in case the user has `{"bridge": "none"}` configured in their docker daemon
- We should prioritize supporting out-of-the-box configurations, but this is just a note in case the user has configured the docker daemon
https://github.com/azerothcore/azerothcore-wotlk/issues/13580

install with docker: note if user has "bridge":"none" configured in their daemon

---

docs/cpp-code-standards.md

Nyeriah patch 1

---

docs/spell_group.md

- https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/SpellMgr.h#L333
- 
Closes

SpellGroupSpecialFlags

---

docs/es/windows-core-installation.md
docs/windows-core-installation.md

- Update of windows-core-installation.md to Spanish 
Closes
- Closes https://github.com/azerothcore/wiki/issues/841

(doc/es) Update windows-core-installation.md

---

docs/spell-effects-reference.md

SPELL_EFFECT_SUMMON "discovery"

---

docs/gameobject_template_addon.md

- FREEZE ANIMATION flag is not used from AzerothCore
related of https://github.com/azerothcore/Keira3/issues/2718

docs: update gameobject_template_addon.md, freeze animation description

---

docs/es/linux-requirements.md
docs/linux-requirements.md

- Add in the title where it talks about Debian, which also works in Debian 12. I do not add 11, because I did not test it, but it should also work, however, for now by adding 12, I think it is enough to clarify that it also works on this operating system.
Closes

chore(linux-requirements) Add Debian 12 to the Debian section

---

docs/es/home.md

- Update the home page of the Spanish sector
Closes

chore. update spanish home page

---

docs/es/home.md

- Apparently, I need to make these changes, so that both the Spanish and English sectors are available. If not, it will always be redirected to Spanish, and the other sector of the site will be disabled. There were also links that were wrong or that in English are used differently.
Closes

chore. Fix broken links

---

docs/quest_template.md

- https://github.com/azerothcore/azerothcore-wotlk/commit/b6c429c5a8c3c127d9a14eef72e5bfb1a796d6bf

Remove `RewardBonusMoney` from `quest_template` to reflect AC changes.

---

docs/page_text.md

Ref: https://github.com/azerothcore/azerothcore-wotlk/blob/master/data/sql/base/db_world/page_text.sql#L19

docs: correct page_text field names

---

docs/es/classic-installation.md
docs/es/installation.md
docs/es/linux-core-installation.md
docs/es/linux-requirements.md
docs/es/macos-core-installation.md
docs/es/macos-requirements.md
docs/es/requirements.md
docs/es/windows-core-installation.md
docs/es/windows-requirements.md

- Linux, MacOS and Windows NavBars/Paths have been updated (to project the same as the English version)
- Created Classic Instaltion in the Spanish Folder and Translated It (majority with the help of google, so it wouldn't be in english).
- Created MacOS Core Installationin the Spanish Folder and Translated It (majority with the help of google, so it wouldn't be in english).
- Corrected in Installation the Path for Classic-Instalation.
The translate may be off or not, may be worded strangely by being european, I can't fully confirm or deny it.
@pangolp

Updated Spanish Docs Folder

---

_includes/azerothcore/sidebar.html
docs/es/client-setup.md
docs/es/home.md

First Request was deleted the origin by mistake, refering to this PR: https://github.com/azerothcore/wiki/pull/962
- Updated "Note" to reflect the English Version in the Client-Setup (ES)
- Added Codeblock to "set realmlist" in Client-Setup (ES)
- Changed Sidebar.html (the spanish part only) to reflect the English version
- Added "Help" onto "Home" (ES)
Closes
@pangolp There was no change in Written Spanish, but im tagging since is your job done (the wiki es)

Simple Changes and Updated Sidebar.html (on the ES side) - Request 2nd Time 

---

_includes/azerothcore/sidebar.html
docs/es/client-setup.md
docs/es/home.md

Reverts azerothcore/wiki#964
Broke build. https://github.com/azerothcore/wiki/actions/runs/9332665923/job/25688789413
To fix later

Revert "Simple Changes and Updated Sidebar.html (on the ES side) - Request 2nd Time "

---

docs/quest_template_addon.md

- 
- 
- azerothcore/azerothcore-wotlk#19116

docs: quest_template_addon: add SpecialFlags 64 and 128

---

docs/useful-sql.md

- Added a SQL Script for viewing the character inventory inside the database
Closes

add inventory SQL Script

---

docs/install-with-docker.md

- add note about install sql files 
Closes

docker: add note about installing module SQL files

---

docs/linux-requirements.md

- 
- 
Progress azerothcore/azerothcore-wotlk#19451

fix(linux-requirements): Debian: update MYSQL installation steps

---

docs/smart_scripts.md

- Adds `TRIGGERED_IGNORE_EFFECTS` as added by ed824de7b803a4f66c2cc35918bb23077db62124

Add new trigger flag for AC change.

---

docs/database-world.md
docs/module_string.md
docs/module_string_locale.md

https://github.com/azerothcore/azerothcore-wotlk/pull/19475

module string

---

docs/ac-dashboard-core-installation.md
docs/linux-requirements.md

docs: improve Debian Requirements and acore.sh installation guide

---

docs/es/linux-core-installation.md
docs/linux-core-installation.md
docs/server-setup.md

- Resolves consistency issues as described in #985 
Closes #985
@pangolp I've made the same changes in the corresponding parts of the Spanish, but there's also some additional text which could do with translation (and some English that was in there before I got there).

Make commands and directories consistent through linux-core-installation

---

docs/realmlist.md

- Adds missing explanation to the localAddress field of the realmlist.
N/A
@pangolp consider adding this to the Spanish also.

Clarify the purpose of the localAddress/localSubnetMask fields of the realmlist table

---

docs/quest_template.md

-  `RewardSpellCast`  was changed to  `RewardSpell` in table `quest_template`
- 
Closes

rename RewardSpellCast to RewardSpell

---

docs/quest_template_addon.md

Corrected previous error about the Loremaster Description. Fixed the headings of the page that were not previously working, corrected some punctionation and removed links that didn't show the mentioned thing(s).
- Fixed the headings
- Corrected an error on the 256 Loremaster Descrition
- Corrected Punction
- Removed Links that didn't work / lead to anything within the page
Closes
@pangolp Changes in the EN

quest_template_addon.md changes and corrections

---

.env-files/Dockerfile.github
.env-files/Dockerfile.gitlab

dockerfile ruby:latest update to allow docker compose
- 
- 
Closes

dockerfile ruby:latest update to allow docker compose

---

docs/debian12-install-guide.md

- refer main guide for debian 12 installation
- 
- 
Closes

Update debian12-install-guide.md: add outdated warning

---

docs/linux-requirements.md

- link to github for MYSQL, OS, GCC/CLang requirements
- remove any hints / steps relevant for old / unsupported OS
- 
- 
Closes

Update linux-requirements.md  - cleanup

---

docs/debian12-install-guide.md

This reverts commit 8309835c90f3aae7da08d8e14a176a58bdcb5c5e.
- the guide was updated in #1005 which i had missed, so no need for a warning here
- 
- 
Closes

Revert "Update debian12-install-guide.md: add outdated warning (#1007)"

---

docs/database-keeping-the-server-up-to-date.md

Duplicated strings
- 
- 
Closes

Update database-keeping-the-server-up-to-date.md - Duplicated strings

---

docs/es/reserved_name.md
docs/reserved_name.md

Update eserved_name.md and es/reserved_name.md

(es) reserved_name.md

---

docs/database-management-tool.md
docs/es/database-management-tool.md

Update 
Create es/database-management-tool.md

(es) database-management-tool.md

---

docs/recovery_item.md

Update description for recovery_item.md

---

docs/linux-core-installation.md

- fix link to server-setup to linux-specific (linux-server-setup)
- clarify that systems services are (Optional) Systemd
- mention journalctl to inspect systemd log entries
Review/Merge after, Conflicts:
- https://github.com/azerothcore/wiki/pull/1024
Closes
prompted by support-forum question regarding systemd https://discord.com/channels/217589275766685707/1308400721628106833/1308400721628106833

linux core installation systemd

---

docs/getting-started.md

And updated to have a newer description
- Removal of the pre-created account mentioned
- Added the link for the account creation.
Closes 
Refering to this: https://github.com/azerothcore/azerothcore-wotlk/issues/5271#issuecomment-2531584823

getting-started.md updated 

---

docs/creating-accounts.md

If player in-game and changes the gm level, needs to relog.
Closes

Added Note in Creating Accounts

---

docs/windows-core-installation.md

- Reordered the paragraph so that the 'this folder' in "There are four DLL files that need to be manually added to _this folder_" was clear.
None

Reorder parargraph for clarity

---

docs/requirements.md

MariaDB not supported

---

docs/item_template.md

- As of 01/08/2025, item_template was modified and the statscount isn't used anymore.
- https://github.com/azerothcore/azerothcore-wotlk/commit/239a641bd7e6ccd4c9ba9c55ba19b80179b4dd14
None

Remove statscount from item_template
