azerothcore/wiki

- docs/Installation.md
- docs/Requirements.md
I went through the installation steps defined in `Installation.md` and `Requirements.md` and clarified any inconsistencies I encountered.
- Added reference to `CMAKE_INSTALL_PREFIX` when referring to the location of the server, build artifacts and binaries.
- prepended `acore` to db names for when setting `MYSQL SETTINGS` for the first time.
- fixed formatting inconsistencies.
> Fix syntax and clarified steps in Traditional Setup Guide

- docs/database-world.md
- docs/scripts.md
- Add documentation for the new script command SCRIPT_COMMAND_MOVEMENT (35)
(see https://github.com/azerothcore/azerothcore-wotlk/pull/1721)
- Add "scripts"-link to "database-world.md" as this seems to be missing
> Documentation for the new script command SCRIPT_COMMAND_MOVEMENT (35)

- docs/quest_poi.md
The "WorldMapAreaId" field is related to the ID of the map where you've to show the QUEST_POI that's found in WorldMapArea.dbc and not in AreaTable.dbc.
Fixed the "WorldMapAreadId" field description.
Noticed that issue when I tried to add quest_poi on custom maps.
Also compared somes quests' WorldMapAreaId field with the ID from WorldMapArea.dbc and it matches everytime.
> Fix description of "WorldMapAreaId" - quest_poi.md

- docs/smart_scripts.md
Update smart_scripts documentation:
- action type SMART_ACTION_SET_REACT_STATE (8) does not support react state "assist" (3)
- renamed action type SMART_ACTION_SET_DISABLE_GRAVITY (60) to SMART_ACTION_SET_FLY and update the parameters (I don't know how this action type actually works so cannot provide further information, but this reflects the implementation of the parameters)
- mark action types 116-120 as not supported
> smart_scripts: update action types 8, 60, 116-120

- docs/Requirements.md
Added `sudo apt-get update` to allow for the newest of each package to be installed and for installation if apt-get has never been updated.
No issues reported.
If you've never ran `sudo apt-get update` in some instances the required packages will not be found.
Ran on fresh instance of 18.04 LTS Ubuntu Server `apt-get install <dependencies>` failed due to `sudo apt-get update` never being performed.
> Update Requirements.md with sudo apt-get update

- docs/creature_template.md
Updating creature_template : missing some fields, and "deleting" non-existants fields.
Some fields were missing from the creature_template doc.
I noticed it while working on creatures. AC Rev : 1f4eefe1bea6d995fa110169afe25ac5c61b0254
Required to improve the wiki.
Compared the wiki and the creature_template table.
Tested by creating new creatures in game.
> creature_template - added missing fields

- _includes/azerothcore/sidebar.html
- docs/Waypoints-Information.md
- docs/event_scripts.md
- docs/script_waypoint.md
- docs/scripts.md
- docs/smart_scripts.md
- docs/spell_scripts.md
- docs/waypoint_data.md
- docs/waypoint_scripts.md
- docs/waypoints.md
- Updated all DB pages concerning waypoints and also updated the scripts documentation on this occasion:
```
scripts
event_scripts
spell_scripts
waypoint_scripts
waypoint_data
waypoints
script_waypoint
```
- Updated ```smart_scripts``` in order to use relative links (missed this in my last PR).
- Provided a new page containing general information about waypoints and linked it under "Other" in the sidebar:
```
Waypoints-Information
```
This page provides information about the 3 different waypoint systems and on the usage of the ".wp" command for game masters.
> Update waypoints and scripts documentation

- docs/Requirements.md
Since commit https://github.com/azerothcore/azerothcore-wotlk/commit/0e6c9a18f4f3f82ec431aad7101bdf58b8f5d63f it is necessary to use at least cmake version 3.8. Ubuntu 16.04 uses version 3.5.1 as default, so you have to install the latest version as described here:
https://apt.kitware.com/
> Update Requirements concerning cmake

- docs/Requirements.md
It seems that after commit https://github.com/azerothcore/azerothcore-wotlk/commit/0e6c9a18f4f3f82ec431aad7101bdf58b8f5d63f there are also build errors on Ubuntu 16.04:
```
azerothcore/src/server/scripts/Northrend/DraktharonKeep/boss_novos.cpp:57:65: fatal error: no matching constructor for initialization of 'const std::unordered_map<uint32, std::tuple<uint32, Position> >' (aka 'const unordered_map<unsigned int, tuple<unsigned int, Position> >')
std::unordered_map<uint32, std::tuple <uint32, Position>> const npcSummon =
^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/unordered_map.h:142:7: note: candidate constructor not viable: cannot convert initializer list argument to 'std::unordered_map<unsigned int, std::tuple<unsigned int, Position>, …
```
> Update Requirements concerning gcc-7

- docs/smart_scripts.md
The first parameter of SAI action "SMART_ACTION_EQUIP" uses ID, not CreatureID.
> doc(smart_scripts): fix parameters for SMART_ACTION_EQUIP

- docs/How-to-create-a-PR.md
- docs/Installation.md
- Update "How-to-create-a-PR" to include additional information concerning the AC git commit template (this should ease up naming and merging of the PRs, as they get the name of the first commit).
- Update "Installation" to enable break on warnings for cmake (similar to Travis, so that contributors hopefully fix all warnings on their local system before creating a PR).
> Update "How-to-create-a-PR" and "Installation"

- docs/game_event.md
Following commit https://github.com/azerothcore/azerothcore-wotlk/commit/42a53837c659d80ee248a1e5ec3ab050ae526249 the logic of "end_time" has been changed, so the documentation also has to be updated.
> Update game_event table description

- docs/smart_scripts.md
Remove "SMART_EVENT_FLAG_WHILE_CHARMED" from the smart_scripts documentation, as it won't be implemented (it could cause many unwanted and hard to test side effects and is not really needed).
> docs(smart_scripts): Remove SMART_EVENT_FLAG_WHILE_CHARMED

- docs/smart_scripts.md
- Update the comment concerning SMART_ACTION_SET_ACTIVE: Grids are never unloaded, but it still takes a few more resources because the objects nearby stay active.
- Add a comment to SMART_ACTION_SET_COUNTER
> docs(smart_scripts): Update SMART_ACTION_SET_ACTIVE & SMART_ACTION_SET_COUNTER

- _includes/azerothcore/sidebar.html
- docs/MySQLtypesC++.md
closes #89 
Rough import from TC if something needs changing just tell me.
> Add MySQL types (C++) from TC

- docs/loot_template.md
Added some examples so the field isn't as ambiguous.
> Add lootmode examples to ***_loot_template.

- docs/Install-with-Docker.md
Added documentation on how to remove the persistent docker volume for ac-database.
- Added documentation explaining how to remove the Docker persistent volume.
https://github.com/azerothcore/azerothcore-wotlk/pull/2947
- Helps users who aren't familiar with Docker.
- Change was requested on a PR
- I've ran the commands step by step in the documentation and they work.
> https://github.com/azerothcore/azerothcore-wotlk/pull/2947

- docs/item_template.md
It was from TC.
It's not an item quality "bind to account", it's a bonding type because it overrides the existing bonding.
There are items that are not heirlooms but bind to accound . There are also items that are heirlooms quality and bind to account but they're not heirlooms but it's widely accepted as "heirloom quality".
> fix: item_template was wrong about gold item quality

- docs/GM-Commands.md
I grouped them together or easier browsing thus breaking the alphabetical order, but this order is just the order of laziness, so why not break it
Also improved the exit code part
> fix: Improve the server shutdown/restart descriptions + group them

- docs/conditions.md
This is taken fron ConditionMgr.h, sadly the condition itself doesn't exist (condition 47) on azerothcore yet (a message warned me in the console, quite neat) but we need it to fix some particular quests loot rewards
but at least the documentation will be ready for when it's ported from TC
> fix: Add info about quest state_mask in conditions.md

- docs/item_template.md
We also need someone to implement these flags or refactor those that are dumb (like real duration time...)
I grepped for all these flags and they were all missing in the core
> fix: Update unknown flags in item_template

- docs/item_template.md
some item types are in weapon slots but they are considered armor
> fix: Add info relation InventoryType/Class

- docs/loot_template.md
The field `MinCountOrRef` has been split into `MinCount` and `Reference` fields a looooong time ago.
> doc: remove deprecated stuff

- docs/mail.md
I don't know the size of the other parameters of the packet, but a mail of 8000 characters works fine. I do'nt know if we can go up to 25000 or 30000. No idea... Needs a dev to find this out, kinda why I make this PR
> feat: Add extra info for mail text length

- docs/GM-Commands.md
- Reorganized the ban commands, one was completely off the table, and the unban commands were in alphabetical order but it's not practical to find so I put them near the ban commands. When you look for banning related, everything is there, no need to scroll, better User eXperience.
- Made it clearer that the $bantime does not need double quotes (else it fails)
- Explained the .ban playeraccount command
> refactor: gm_commands ban commands

- docs/Installation.md
- macOS AC build is no longer broken
- corrected minor issue with mysqlclient lib path on newest macOS+brew
> doc(installation): fix macOS

- docs/GM-Commands.md
I've read through the source + it looks like the respawn command will accept a target if given one. I've tested ingame to confirm. This PR updates the docs to reflect this.
#282
See docs on related issue. I've verified that the behavior I'm documenting in source code + ingame
> Add more details to `respawn` command description

- docs/creature_template.md
Add further clarification on raid mode differences and adding battleground brackets:
1. Explain differences between a raid with 4 difficulties vs 2 difficulties (ex. ICC vs Naxx)
2. Add battleground level brackets (alterac valley, isle of conquest)
3. Explain why hardmodes within Ulduar do not have their own template
Current format wasn't abundantly clear on raidmode differences and did not contain level brackets for battlegrounds with NPCs (AV/IoC)
> Further clarification on difficulty_entry_x

- docs/Installation.md
- Make it clear that sources should be downloaded using the `git` command (some users didn't understand it)
- Make it clear to use **git bash** as terminal for Windows users
> doc: improve classic installation

- docs/Requirements.md
Sequel Pro is no longer maintained, Sequel Ace is a new fork of it.
> docs(Requirements/Mac): replace sequel-pro with sequel-ace

- docs/GM-Commands.md
* Alphabetize GM Commands
* Place main commands before subcommands (eg. .teleport comes before .teleport name)
* Order commands starting with `un` as if they did not have the `un` prefix.
* This places them next to their opposite command
* For example, possess will be next to unpossess, and both will be in the `p` section (eg. 1. player learn, 2. possess, 3. unpossess, 4. quest)
* Place `showarea` and `hidearea` commands next to each other, in the `s` section
#213
> Alphabetize GM Commands

- docs/Requirements.md
seeing https://github.com/azerothcore/azerothcore-wotlk/issues/4096  and others in discord VS17 seems to not work with nodiscard and we should deprecate vs17 anyways. I just cant find where in the core...
> chore(requirements): Remove vs17

- docs/PageTextMaterial.md
- docs/character_action.md
- docs/character_social.md
- docs/creature_summon_groups.md
- docs/game_event_battleground_holiday.md
- docs/group_member.md
- docs/groups.md
- docs/linked_respawn.md
- docs/petition.md
- docs/petition_sign.md
The idea is to transform the HTML tables into markdown tables as described in the issue
https://github.com/azerothcore/wiki/issues/247
https://github.com/azerothcore/wiki/search?q=%3Ctbody%3E
https://jmalarcon.github.io/markdowntables/
https://www.tablesgenerator.com/markdown_tables
> Converting from HTML to Markdown

- _layouts/azerothcore.html
closes https://github.com/azerothcore/wiki/issues/267
The sole purpose is to remove the self-generating table of contents which makes some wiki pages look really awful.
However I don't know if removing this line would fix the issue, but after the changes here https://github.com/azerothcore/wiki/pull/379 it is clear that it has something to do with this line as it made it worse in some pages
> chore(azerothcore.html): Stop the wiki for generating table of contents

- _layouts/azerothcore.html
I suggest reducing the `h_max` from 3 to 2, so that the content is not so extensive. Because otherwise, in certain pages, it becomes very long. Originally, it had that value I think, but I changed it at one point, thinking it was the reason for the error in the `git-wiki-toc` message but luckily, that error was repaired by Yenohal.
> update `h_max` azerothcore.html

- docs/Installation.md
Ace.dll is no longer required to run azerothcore. This PR removes it from the list of required DLLs in the Windows installation instructions.
A recent PR to the Azeroth Core repo, https://github.com/azerothcore/azerothcore-wotlk/pull/3450, removed the need for a separate `ace.dll` file. See [the comment at the bottom of the PR](https://github.com/azerothcore/azerothcore-wotlk/pull/3450#issuecomment-724737882) for a confirmation of this.
* I just upgraded my server to the latest version of AzerothCore, and verified that it can run without `ace.dll`
* @Kitzunu has also tested and confirmed that AzerothCore can run without `ace.dll`
> Remove ace.dll from list of required dlls in Windows installation instructions

- docs/GM-Commands.md
Splits the syntax for GM Commands into a separate column for legibility.
Hard to quickly see where command syntax ends and description of the commands begins.
Documentation - no testing.
> Add Syntax Column to GM-Commands.md

- docs/Install-with-Docker.md
Hello ! If you follow the docker installation guide step by step and your server is not on your local network, you will likely come across this problem where, in the client, you will be able to log in your account but unable to move forward into the realm. It most likely comes from the wrong IP address in acore_auth.realmlist
I think this is a very usefull information for the first time user. Also this information is disclosed in the classic installation guide, step 6, but not in the docker one. So this is what I propose to add in the docker installation guide.
There are a few issues over the internet related to this, for example : https://stackoverflow.com/questions/54852245/how-to-resolve-sticking-in-realm-selection
Thanks !
> Add info about realmlist in docker guide

- docs/realmlist.md
https://github.com/azerothcore/azerothcore-wotlk/pull/4929
Was always these restrictions with float unsigned, but with the changes in the PR above to CHECH (`col`>=0) the SQL will give a different error.
> chore(realmlist): Update info

- docs/character_stats.md
> chore(character_stats): Update info

- docs/creature_formations.md
> chore(creature_formations): Update info

- docs/creature_text.md
> chore(creature_text): update info

- docs/item_enchantment_template.md
> chore(item_enchantment_template): update info

- docs/pool_creature.md
> chore(pool_creature): update info

- docs/pool_gameobject.md
> chore(pool_gameobject): update info

- docs/spell_enchant_proc_data.md
> chore(spell_enchant_proc_data): update info

- docs/spell_proc.md
> chore(spell_proc): update info

- docs/database-only-quick-setup.md
- Replace `docker-compose` with `docker compose` as the former is now deprecated by Docker
- Remove non-detached command from the guide
- Fixed `DOCKER_DB_EXTERNAL_PORT` and `DOCKER_DB_ROOT_PASSWORD ` names
Note: this will work only when these bugs are fixed:
- https://github.com/azerothcore/azerothcore-wotlk/issues/5429
- https://github.com/azerothcore/azerothcore-wotlk/issues/5431
> docs: improve db-only docker setup

- _config.yml
Blog is not used, and I dont see a reason to have it has we have discussions on main repo
Dont need download button for wiki source code
> chore(wiki): Disable blog and fix English

- docs/creature.md
- docs/gameobject.md
Added documentation for the `areaId` and `zoneId` columns in the `creature` and `gameobject` pages
Describe what areaId and zoneId are and how these columns are populated
Closes #512
I know these columns are useless from the core's perspective but I actually found them useful while working on azerothcore/azerothcore-wotlk#6088. I would have found a solution more easily if documentation for these columns had been available.
Could not get either installation method to work lmao so I just copied the entire markdown into an online markdown editor thing to inspect them
> Add documentation for areaId and zoneId

- docs/how-to-use-changelog.md
- docs/project-versioning.md
- Removed phase 3, after years of development we never imported any changes to the released branches, therefore, from now on we only support security fixes after a new stable version has been released.
- Added prerelease metadata to our semver standard to support the new changelog system
This PR is related to: https://github.com/azerothcore/azerothcore-wotlk/pull/6350
> feat: new versioning rules

- docs/creating-accounts.md
> fix: typo `worlserver` to `worldserver`

- docs/home.md
This is just fixing some minor spelling/grammar mistakes and phrasing on the home page to make it clearer. 
The only questionable one was the first line (original was an incomplete sentence saying "AzerothCore is a complete Open Source and Modular solution for MMO") which is a sentence that could be ended a few different ways ('emulation', 'framework', even 'gaming'.) I went with 'development', but see what you think.
Closes
> Fix minor spelling/phrasing issues with home.md

- docs/linux-requirements.md
Previously, I remember that the cmake update via python, appeared, but then for some reason I don't know it was removed. However, it still works, I tested it last week.
Because currently the emulator uses clang10 or higher, I attach a link from stackoverflow that helped me to perform the update and thus, to compile the emulator in Debian 10.
Closes
> Upgrading cmake and clang11 on Debian 10

- docs/linux-requirements.md
The package "libmariadbclient-dev" package has been removed in MariaDB 10.5 and installing it will fail if you have MariaDB 10.5 or newer. Its functionalities have thus been implemented into the "libmariadb-dev" package.
> Removed libmariadbclient-dev package

- docs/spell_proc_event.md
Add the missing procPhase to spell_proc_event page
[From here](https://github.com/azerothcore/azerothcore-wotlk/blob/89deb60d43cb4aa1c51214db9ad423b65f94f522/src/server/game/Spells/SpellMgr.h#L240)
Closes
> Add procPhase to spell_proc_event

- docs/how-to-create-a-db-pr.md
Noticed the steps were all numbered "1" and clarified the naming convention as it could be misunderstood, such as in this PR: https://github.com/azerothcore/azerothcore-wotlk/pull/12034.
Whoops.
> Fix steps numbering and clarify SQL naming convention.

- docs/ac-dashboard-core-installation.md
`curl`, `sudo` (Needed for `acore.sh`), and unzip (needed for deno) does not come with the RPI debian bullseye image. This PR corrects this.
N/A
> Added three necessary programs to the dependency list for ac-dashboard-core-installation.md 

- docs/item_instance.md
Corrected two typos. `MEDIUNINT` to `MEDIUMINT` and `itemEnry` to `itemEntry`.
N/A
> 2 typos in item_instance.d

- docs/linux-requirements.md
Possible typo `OpenSLL` to `OpenSSL`
Closes
> typo found in linux-requirements.md

- docs/conditions.md
Right now, it sounds like it's just the race value and not a racemask. The core handles it like a racemask, so it should be made clear that it is a racemask here.
> Adjust the wording of the conditions table regarding race condition.

- docs/final-server-steps.md
Fixes an incorrect link in the Final Server Steps footer.
Closes #771
> fix: incorrect link in final server steps footer

- docs/update.md
Removes section on updating with the deprecated DB assembler and replaces it with using the auth/worldserver's built-in updaters.
Updates version of DB you need to check for, will need to update the `upgrade-from-pre-3.0.0-to-latest-master` page to detail the more recent DB squashes as well as their respective commits to checkout.
Cleans up a couple grammar/spelling mistakes.
> Remove reference to DB Assembler, clean up spelling/grammar.

- docs/item_instance.md
- docs/item_instance_enchantments.md
-  The 36 space seperated string in the Enchantment Field is Confusing unless given a bit of context this documentation attempts to do that.
> Added Detail about the Enchantment Field in Item_Instance.

- docs/networking.md
Adds MySQL CLI command line since the CLI was used from https://www.azerothcore.org/wiki/database-installation
- Provides MySQL CLI Commands. Most of the Linux Installation is Copy and Paste. This will keep in the flow of that syntax. 
Closes
> Adds MySQL CLI

- docs/es/linux-core-installation.md
- docs/linux-core-installation.md
- docs/macos-core-installation.md
* Current section "Linux Core Installation" [mentions](https://www.azerothcore.org/wiki/linux-core-installation) the old `TOOLS` parameter. Currently, this parameter has been replaced with `TOOLS_BUILD`. It is also worth specifying the value of this parameter as "all", since map tools will be required in the following steps of the instruction.
> Changed cmake TOOLS parameter to actual TOOLS_BUILD

- docs/windows-core-installation.md
- docs/windows-requirements.md
- Updates the Windows requirements page to recommend OpenSSL 3.0 instead of 1.0/1.1.
- Also adds a path to find `legacy.dll` in the Windows core installation page like the other `*.dll* files.
> Change OpenSSL section of the Windows install guide to suggest 3.0 instead of 1.0/1.1

- docs/sql-standards.md
- Create a standard on the capitalization of SQL tables and columns based on some feedback from the Discord server:
Tables: snake case (creature_loot_template) lowercase, underscores between words.
Columns: upper camel case (RaceMask) uppercase first letter, no space between words.
If approved, I can go through and change tables/columns to actually match this standard (or whatever standard we choose), since there is currently a lot of inconsistency regarding this subject.
> Create SQL standard for capitalization of SQL tables/columns.

- docs/sql-standards.md
- Creates a defined way to handle acronyms in SQL column names.
> Update SQL naming standard to accommodate acronyms.

- docs/creature_template.md
Adding documentation for the flag CREATURE_FLAG_EXTRA_HARD_RESET added in [CreatureData.h](https://github.com/azerothcore/azerothcore-wotlk/commit/d464ee7083f6321aa4d33c3f68c2432b247c38e0#diff-ff0e6d9ad5d397cd8b04eee23afc146d89fd5d55940d02e321365bb9de883841)
> updated not documented flag: CREATURE_FLAG_EXTRA_HARD_RESET

- docs/home.md
- Remove home warning about OpenSSL 3.x because it's now supported
- 
Closes
> remove OpenSSL 3.x warnings

- docs/ac-dashboard-core-installation.md
The current worldserver and authserver fails to load if you don't have the worldserver.conf and authserver.conf. The ./acore run-{world,auth}server commands also gets stuck in an infinite loop and bails (nice check!) due to worldserver and authserver returning a non-zero exit value.
This was required to make this work under Ubuntu on WSL2 running on Windows 11.
- 
- 
Closes
> ac-dashboard-core-install: Fix conf file section

- docs/macos-core-installation.md
- Homebrew installs packages in different directories depending on if you have an Intel CPU or an Apple Silicon CPU. This is described in the first real paragraph of the [installation docs](https://docs.brew.sh/Installation):
> The script installs Homebrew to its default, supported, best prefix (/opt/homebrew for Apple Silicon, /usr/local for macOS Intel.
- To account for this, I added a version of the CMake command that uses the `/usr/local` pathing for Intel CPUs.
- For consistency, I also changed the ssl version in the CMake command to `openssl@3` from `openssl@1.1` to be consistent with [the MacOS requirements](https://www.azerothcore.org/wiki/macos-requirements) that ask for `OpenSSL ≥ 3.0` and have you `brew install openssl@3`.
No related issues, but closed my own before I ever …
> Add version of CMake for Intel Mac

- docs/install-with-docker.md
This PR adds some basic information about taking backups on the "Install with Docker" page.
Technically, these commands support most installation methods for AzerothCore. May be worth making this a dedicated page instead?
> docker: add section about taking backups

- docs/linux-core-installation.md
- docs/linux-requirements.md
- docs/macos-core-installation.md
- docs/macos-requirements.md
- docs/windows-core-installation.md
- docs/windows-requirements.md
While following the "Classic Instalation" either of the OS you choose, will correctly continue the next page.
Windows Requirements will take you to Windows Core, instead of making you choose once again, what OS you're doing the setup for it. 
Linux / MacOS / Windows "Requirements" Files have their navbars (going foward) correctly pathed to their respective OS
linux-core-installation | macos-core-installation and windows-core-installation.
Within the the "Installation" files have their navbars (going back) correctly pathed to their respecive OS
linux-requirements | macos-requirements and windows-requirements.
Still in Installation, I've changed the "Required software: See Requirements before you continue." to their respective OS requirements.
Closes
Remember that the wiki is currently …
> Classic Instalation Wiki - Respective NavBar Path relative to the option chosen.

- docs/spell_custom_attr.md
- https://github.com/azerothcore/azerothcore-wotlk/pull/19209
- Also add the long forgotten SPELL_ATTR0_CU_BYPASS_MECHANIC_IMMUNITY
- Add description to SPELL_ATTR0_CU_IGNORE_EVADE
Closes
> Spell Custom Attributes - SPELL_ATTR0_CU_ONLY_ONE_AREA_AURA

- docs/linux-requirements.md
- 
- 
Progress azerothcore/azerothcore-wotlk#19451
> fix(linux-requirements): Debian: replace MariaDB by MYSQL

- docs/quest_template_addon.md
Added 256 to the Special Flags.
Changed from a List to Table
- Added 256 (Loremaster) SpecialFlag into the SpecialFlag 
- Changed List to Table Format
Closes
@pangolp Changes to the EN file. 
Request of: https://github.com/azerothcore/azerothcore-wotlk/pull/19962#issuecomment-2351781425
> Added 256 Loremaster SpecialFlag

- docs/aws-tutorial.md
> Update aws-tutorial.md - drop reference to old Ubuntu LTS

- docs/linux-requirements.md
- default-libmysqlclient-dev on Debian installs mariadb libraries
- therefore install libmysqlclient-dev via mysql software repository
- 
- 
Follow-Up to azerothcore/azerothcore-wotlk#20003
Closes azerothcore/azerothcore-wotlk#19999
> fix(linux-requirements): Debian: fix MYSQL installation steps

- docs/quest_template.md
https://github.com/azerothcore/azerothcore-wotlk/blob/97aaf8490cdde12d194558c4ee5acf037b5cd1b5/src/server/game/Entities/Creature/GossipDef.cpp#L535
> Update quest_template.md - QuestType hasn't #3

- docs/game_event_arena_seasons.md
- docs/game_event_battleground_holiday.md
- docs/game_event_seasonal_questrelation.md
- `game_event_arena_season.md`
- Header "eventEntry" has been given a link to `game_event.eventEntry.md`
- Added a table with eventEntry, Season and Comment for people know what they mean in the database.
Example below:
| eventEntry | season | Comment (not part of the DB)             |
| ---------- | ------ | :--------------------------------------- |
| 75         | 1      | TBC - Season 1: "Gladiator"              |
- `game_event_battleground_holiday.md`
- Header "eventEntry" has been given a link to `game_event.eventEntry.md`
- Added a table with eventEntry, bgflag and Comment for people know what they mean in the database.
Example below:
| eventEntry | bgflag        | Comment (not part of the DB)          |
| ---------- | ------------- | :------------------------------------ |
| 18 …
> game_event_%.md - Updates

- docs/create-a-module.md
The technical article on how to create a module is lacking a link to the catalogue
prompted by a question asked on discord asking for "a page describing the process of presenting a new module for AzerothCore" 
- Add link to catalogue
- 
Closes
> add link to catalogue on the how to create a module page

- docs/es/server-setup.md
- docs/server-setup.md
**Correction in the file in English**.
**Update of the files in Spanish**.
> (es) Update server-setup.md

- docs/es/guide-to-triaging.md
- docs/guide-to-triaging.md
https://www.azerothcore.org/wiki/guide-to-triaging
Other links -> [ChromieCraft mods](https://raw.githubusercontent.com/chromiecraft/chromiecraft/main/.github/CC_SERVER_INFO)
404: Not Found
Closes
> fix: link to cc server info

- docs/es/the-modular-structure.md
- docs/the-modular-structure.md
When trying to access the documentation about Script hooks in the file the-modular-structure.md Github returns a HTTP 404. I noticed the file that is trying to find is using the first letter capitalized, and since GitHub's file linking is case-sensitive I am opening this PR to fix the documentation.
- 
- 
Closes
> (fix): Changing URL to lower case to fix HTTP 404 in page

- docs/debian12-install-guide.md
- docs/linux-requirements.md
This is a fork of #1023 with the requested changes cause the author hasn't responded yet.
Closes #1023
> Update MYSQL docs continued

- docs/es/linux-core-installation.md
- docs/linux-core-installation.md
- docs/linux-server-setup.md
- docs/macos-core-installation.md
- docs/macos-server-setup.md
- docs/server-setup.md
- docs/windows-core-installation.md
- docs/windows-server-setup.md
There are many support questions in discord with issues on the server starting that stem from incorrect DataDir paths/missing client Data altogether. Most of these are from linux users. I think this comes from linux users getting an incomplete explanation of the client data
The Windows and MacOs core installation pages also link to the general server setup page
> make server-setup only link to OS-server-setup

- docs/faction.md
- Corrected Header Information
- Changed "Content" Table to now have:
| FactionTemplate.ID (DBC) | FactionTemplate.Faction (DBC) | Faction.Name_Lang_enUS (DBC) | Faction.ReputationIndex (DBC)
| -- |  --  | --  | -- |
This currently matches what's shown on Keira
With this change the player/user has the both (important) IDs when using azerothcore.
FactionTemplate.ID = Used by creature_template as an example
and
FactionTemplate.Faction = Used by reputation gains as an example the .modify rep command
> Updated faction.md
